#ifndef EMBED_RESOURCE_LOADER_H
#define EMBED_RESOURCE_LOADER_H

#include <cstddef>
#include <string>

// This file gets auto-generated by CMake from your resources:
#include "embed_resource/resources.h"

class Resource {
public:
  Resource(const char *start, const std::size_t len) : resource_data(start), data_len(len) { }

  const char * const &data() const { return resource_data; }
  const std::size_t &size() const { return data_len; }

  const char *begin() const { return resource_data; }
  const char *end() const { return resource_data + data_len; }

  std::string toString() const { return std::string(data(), size()); }

private:
  const char *resource_data;
  const size_t data_len;
};

#define LOAD_RESOURCE(x) ([]() { return Resource(res::_resource_##x, res::_resource_##x##_len); })()

#endif // EMBED_RESOURCE_LOADER_H
